### ISSUE TITLE
Is there any instructions for install and use on Mac?

### ISSUE THREAD

**Issue by LifeWorks** [Keep-Passion/ImageStitch#26]
Came across the repository. I would like to use it but it seems there are c++ code I need to compile first?

**Comment by Keep-Passion** [comment]
No, the C++ code is used for GPU acceleration. I have compiled one for windows. But the version of GPU mode is not stable. If you can not use it, please turn to CPU mode

**Comment by LifeWorks** [comment]
Thanks for the reply. I will try the CPU mode then.
