### ISSUE TITLE
The software linked in your paper has a faulty url

### ISSUE THREAD

**Issue by Edodums** [Keep-Passion/ImageStitch#27]
This is the url that you're redirected to if you try to download the software ( the one mentioned in your paper )
http://ima.mgedata.cn/static/software/ImageAnalysis_V_1%20%20%20%20%20%20.4_Setup.exe 

To download it you've have to delete te %20 part , could you fix it for the other people who can't figure out why they're redirected to a 404 page?

It would mean a lot for me, also because I want to cite your software in my thesis.

**Comment by Keep-Passion** [comment]
Thank you for your advisement. I have fixed that url

**Comment by Edodums** [comment]
❤️

**Comment by Edodums** [comment]
If I must I'll say something else :
- https://www.mgedata.cn/app_entrance/microscope , when you press the "en" button doesn't translate;
- the setup of the installer is only in chinese;
- after you've successfully installed the software it doesn't open anything, does it work for you?

**Comment by Keep-Passion** [comment]
Thank you for your advice. The software in 'https://www.mgedata.cn/app_entrance/microscope' asks you to upload data to exchange for the software license. Recently, we will publish a new version of MicroStitch with a new stitching algorithm and safely software license. All the questions that you proposed will be handled in the latest version. If you like, I will invite you to test software after software online.

**Comment by Edodums** [comment]
Oh, ok, didn't know that.
Well, it depends on if I'm available, I'm quite tight on schedule until March 😄, but you can contact me anyway.

Thank you for your work,
Best regards,
@Edodums
