### ISSUE TITLE
error module 'myGpuFeatures.myGpuFeatures' has no attribute 'detectAndDescribeBySurf'

### ISSUE THREAD

**Issue by vladimircape** [Keep-Passion/ImageStitch#8]
module 'myGpuFeatures.myGpuFeatures' has no attribute 'detectAndDescribeBySurf'
when I tried python Main.py

**Comment by vladimircape** [comment]
also happend
The error is :  from myGpuFeatures import myGpuFeatures
ImportError: DLL load failed: 找不到指定的模块。

I check by inspection, you have errors in dependecies on pyd file

**Comment by Keep-Passion** [comment]
First, What's your operating system? The code only works on windows. 
Second, Have you ever unzip the file "myGpuFeatures.rar"?
Third, I only test on python36 and OpenCV-3.3.1.
