### ISSUE TITLE
from myGpuFeatures import myGpuFeatures

### ISSUE THREAD

**Issue by nxm19830306** [Keep-Passion/ImageStitch#9]
ImportError: DLL load failed: 找不到指定的模块。

Could you upload myGpuFeatures.py file? Thanks

**Comment by nxm19830306** [comment]
How to solve this problem? Thanks

**Comment by Keep-Passion** [comment]
Please unzip my GPU features. rar in your windows system

**Comment by nxm19830306** [comment]
Yes, I unziped "my GPU features. rar" in my win10 system,but it does't work. The CUDA version is 9.

I used the anaconda3 to manage the software. The install software is followed:
python             3.6.12
certifi               2020.12.5
cycler                0.10.0
decorator             4.4.2
imageio               2.9.0
install               1.3.4
kiwisolver            1.3.1
llvmlite              0.36.0
matplotlib            3.3.4
networkx              2.5.1
numba                 0.53.1
numpy                 1.19.5
opencv-contrib-python 3.3.1.11
opencv-python         3.3.1.11
Pillow                8.2.0
pip                   21.1.1
pyparsing             2.4.7
python-dateutil       2.8.1
PyWavelets            1.1.1
scikit-image          0.17.2
scipy                 1.5.4
setuptools            52.0.0.post20210125
six                   1.16.0
tifffile              2020.9.3
wheel                 0.36.2
wincertstore          0.2

**Comment by Keep-Passion** [comment]
I have update requirements.txt，it can work on my computer

**Comment by Keep-Passion** [comment]
If it helps you, please star this repo and sponsor to me if you like

**Comment by fanweiya** [comment]
@nxm19830306 
you can revise ImageUtility.py "from myGpuFeatures import myGpuFeatures" to "import myGpuFeature" and only sift mthod is available on GPU.

**Comment by nxm19830306** [comment]
&nbsp;This problem is fixed, thanks. 
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人: "Keep-Passion/ImageStitch" ***@***.***&gt;;
 发送时间:&nbsp;2021年6月9日(星期三) 中午12:03
 ***@***.***&gt;;
 ***@***.******@***.***&gt;;
 主题:&nbsp;Re: [Keep-Passion/ImageStitch] from myGpuFeatures import myGpuFeatures (#9)

 

 

 
@nxm19830306
you can revise ImageUtility.py "from myGpuFeatures import myGpuFeatures" to "import myGpuFeature" and only sift mthod is available on GPU.
